{"name": "test_fails", "status": "skipped", "statusDetails": {"message": "XFAIL intentional demo fail\n\nAssertionError: assert 2 == 1", "trace": "@pytest.mark.xfail(reason=\"intentional demo fail\", strict=True)\n    def test_fails():\n>       assert 2 == 1\nE       assert 2 == 1\n\ntests\\test_smoke.py:8: AssertionError"}, "start": 1759508133649, "stop": 1759508133650, "uuid": "674c1faa-9324-4986-85eb-59f9aecec1bb", "historyId": "654d579774cbafe816589902b7739b1b", "testCaseId": "654d579774cbafe816589902b7739b1b", "fullName": "tests.test_smoke#test_fails", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_smoke"}, {"name": "host", "value": "סלווא_נעום"}, {"name": "thread", "value": "21960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_smoke"}], "titlePath": ["tests", "test_smoke.py"]}